name: infection_protection_app

# ?: `compose.yaml` is the preferred file name vs `docker-compose.yaml` or `compose.yml`
# ?: CLI Commands will ignore the others if `compose.yaml` exists

include:
  - path:
    - compose-mongo.yaml
    - compose-mongo.override.yaml
services:
  app:
    image: NLCaceres/infection_protection_backend_host
    pull_policy: never
    container_name: infection_protection_app
    build:
      dockerfile: Dockerfile.runner
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ./src/main/resources/.env
    depends_on: # ?: Expands to set `restart: false, condition: service_started, required: true`
      mongodb:
        condition: service_healthy
    networks:
      - main

networks:
  main: