name: mongo-express

# - Provides a GUI for a local Mongo instance
services:
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: "no"
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false
      # - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/
    networks:
      - infection_protection_app_main

networks:
  infection_protection_app_main:
    external: true
