name: infection_protection_app

include:
  - compose-mongo.yaml

services:
  app:
    image: NLCaceres/infection_protection_jar_backend
    pull_policy: never
    container_name: infection_protection_app
    build:
      dockerfile: Dockerfile.jarBuilder
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ./src/main/resources/.env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - main

networks:
  main: