name: mongo_network

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports: # ?: Port value before the colon is available to the HOST; the Port value after is the SERVICES'
      - 27017:27017
    volumes: # ?: Similar to "PORT:PORT", I SEE mongodb-data (as the host), the services store data in the container "/data"
      - mongodb-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false
      # - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
volumes: # ?: Volumes are created when docker compose is run IF they aren't already created
  mongodb-data:
