FROM eclipse-temurin:17-jdk-alpine AS builder

RUN apk upgrade --no-cache && apk cache clean

COPY . /app/src/

WORKDIR /app/src

RUN ./gradlew bootJar

# RUN STEP
FROM eclipse-temurin:17-jre-alpine

RUN apk upgrade --no-cache && apk cache clean

EXPOSE 8080

USER 1001

COPY --from=builder --chmod=0755 \
  /app/src/build/libs/infectionprotection_backend-0.0.1-SNAPSHOT.jar \
  /app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]